apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nolongerevil
  namespace: argocd
spec:
  project: homeassistant
  sources:
  - repoURL: https://github.com/metalnet/infra
    targetRevision: HEAD
    path: kube/apps/homeassistant/nolongerevil
  destination:
    server: https://kubernetes.default.svc
    namespace: homeassistant 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
  
