---
- name: download disk image
  get_url:
    url: "https://cdimage.debian.org/cdimage/openstack/current/{{ image_filename }}"
    dest: "/var/lib/vz/template/qemu/{{ image_filename }}"
    checksum: sha1:https://cdimage.debian.org/cdimage/openstack/current/SHA1SUMS
  register: disk_image
- name: check if the template already exists
  shell:
    cmd: pvesh ls /nodes/pve/qemu |cut -c14-
  register: vm_ids
  changed_when: false
- name: destroy existing template
  shell:
    cmd: "qm destroy {{ vm_id }}"
  when: disk_image.changed and vm_id in vm_ids.stdout_lines
- name: create template
  shell:
    cmd: |
      qm create "{{ vm_id }}" --name debian-template --memory 1024 -net0 virtio,bridge=vmbr2
      qm importdisk "{{ vm_id }}" /var/lib/vz/template/qemu/{{ image_filename }} local-lvm
      qm set "{{ vm_id }}" --scsihw virtio-scsi-pci --scsi0 "local-lvm:vm-{{ vm_id }}-disk-0,discard=on,ssd=1"
      qm set "{{ vm_id }}" --ide2 local:cloudinit --boot c --bootdisk scsi0 --serial0 socket --vga serial0 --ipconfig0 ip=dhcp --sshkey .ssh/id_rsa.pub --agent 1
      qm template "{{ vm_id }}"
  args:
    executable: /bin/bash
  when: disk_image.changed or not vm_id in vm_ids.stdout_lines
