apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://metallb.github.io/metallb
    targetRevision: 0.16.1
    chart: metallb
    helm:
      releaseName: metallb
  - repoURL: https://github.com/metalnet/infra
    targetRevision: HEAD
    path: kube/core/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged

