apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 41.0.2
    helm:
      releaseName: traefik
      valueFiles:
      - $values/kube/core/traefik/values.yaml
  - repoURL: https://github.com/metalnet/infra.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/metalnet/infra.git
    targetRevision: HEAD
    path: kube/core/traefik-routes
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true

