{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-discord-config",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-discord-config",
        "namespace": "monitoring"
      }
    },
    "encryptedData": {
      "alertmanager.yaml": "AgCI29g0+jK/KAlV8ZO3AvKfZfU2uxgbGZn5GtwvGpg+QPoektBxZFGb/ZPaJlmjVdvJjKgfdMCgg6Vg9pyGTThwfWqAvO9JLJp8cnj8AcD1xrY2j6gYaCQEd+U0LSGl2484Q/LlFtFcas1TkMof3tjiMNU1dmhFuA9mWfrzKeobX0EnTxhkOtZAq02nNmcap3f7FLKhjmIyi06ChceWUQ14JQ02fuog2CQKpHUU1uW/jFN7kc/lfTfZoQL6w8HwGnX3Kt/ln2iv4TGBmgY9EJlXsT+7Q2akCKdL+MK1qKaAVb03ZZ8mGIuLGdBmAEYpysIQgJOW81RZrmvS9cI9IpiDGv35MXchi6AIcHaVK2PiozgkcVLwJVsSRM8cI6yNb2iEWILFsx1z+f+JchF2ctIr+27QD0wu1mg/WnB3AP00f9x5ZrdGMuBzYR2+34fUkr+/Oo8lpx0gnvxtimzldhGdiP2v18EeAAUdxYFCOS0UhYgCSlKLgk6wXZwG07Yd4072kuztVUCEz6h8jqglnB/sedAZOmfPf8CID/ypuLxe9fhc2HWLxzeOt8WBjIsepbUTHOl0AIF+njjuL2dQKzfFan9yO2zy6hyVsWKCFC7wAy/2d5xvi/5DDAm7O1lMjFTIh67uZ9ui3gENh5ss0if+2foTypqTQ46EXy4A4t7U/Utc0psR1O75+lFZkm0DVTk4RLp9ffIocDOMXC81vS5Dx8pFRRseWMH15Ata2v6wsFBXU6zGXZ7dUqua/5y2gJXuaXwXPluLT3SyIEZzTZnGnz8Gn6pfBZ2zDFR9m5+SLXOwQZYTzTeWO1eb8ZjjHdIwmdg1z4JDLpsb5lwcl9oJxxkmE2AnFiLJkVBOMm0SDV8TS7QpA6D9cpyFx7GTviOIwGQ1aPiMoRpcuQW6NcGnsLVAImbedz9iMX7CjUCG3Dx8w5gm+BjyPMRm1XEgF8aFvJTxKW2OeOUEKfeHOo2kHVrvvmEfJKfrNJXUgRgNaBpdNOiEw4Ek6b7uQKIRP4HQk0+44oMwnIcHUZhG07bvrzKNr6VkJCSk+5zDDSjyqSqgHHxBnAz8ovAQlRXIGqQtAdebJeNE+OpNY3MbdckYWbu8wU+Lvn4mSPlSn/oBCmNER9yji74QP2R7lMEcycRIql4R0WBJOE3gDtRF0Zg1E5Br5eQSQSX/TCUauP3YjrFHUK/Btx1gFwczNWQAC35wIEByjFhLxOHVXy8YYZx7RrIE6rU3mpMeMSxRePQMZ9pUu4myQEGi4vTYyplBwt66FCMyiQanKSi/AYhb6cf4eZlvGJc="
    }
  }
}
