{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-discord-config",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-discord-config",
        "namespace": "monitoring"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "alertmanager.yaml": "AgCAg/YCbQcQgLbpqEUO9HjFWZWeUS9+EFfkbcKp2KIhs/31OLH3NJgByNQ8v+ado6syfUns45h8igLlMexsM09JryK+AF0fgOlhlfhKJisQXv2oD3cMWHE9fZDUhZats/KnpmggB6vJ9tvukN9oSHfKLkZwx2iZf48Wt4ogScc6zxkt4dQcEL4GN/48nfJ1EN3fC4VTOE/kXIoWpc5YGL+4vMTFoAtaZxoJNRnuBr/9i/DyfyEbCtltgxeP7plSMvxHBtYLBy2wP+yLW230rg822LvZyC8iO78ITAS7Dy2PqtfZBpZYsF7C3CzRDQNVzLDk9L26ZtGUA3ZCTwHizf1EzwNXmTOv/xbju5sxO3tyaWqKcHdxtC7ruun7eLvWPOX6NdILDUhvDxqOKHpmS+JAi9Qj3iwDVed8jyaz5F9HRBqTMCa229sU5+G6L1tNkAdHZa8/lrseqnUG47KAC6bdCw2BLF+BHam4kWqa8VYvXMzCdZaTmSsDlpoJn6KAndYPiJy6y0AzNl91rNzPtsVVHSMd06h9Ilc6VIZfbd+1CG7fsl7FJZk8elmk8ZxBOhqepE4qCzBPjXLF98nNKBlN8OLAOT2SysuCO/cMvz+hxMiWZM6eJpSiv4VyHFMXnZsdoIiwpWtxoFTvUSTo9mvRwToK3S/VA0KpwHwYsfRhnkkbk+HfOpq/KsiWYe8XYCWO7geqWgJUFQAS+u9faGCCdxBNlM32jQyJVSR6WfdyclfSZvxr8N7Ka2W3ygfNqQY/9O/rhd3QmMp2MuNhUp5RcCG351YNQVX2lZONZ7uOAz9GhZDTcYuPsOsQqxBEHvDOa3RPDg3kH+UyxmT6FeBBtOiob+OK3+/ZI9ugo2k+MS75lZ5Ci49rJ+vAld1FvdPaGrtMFNEdzGF4Mf+ujVEdyzXDmTSNvID9H6MApx10l8Yin1/z689C5el/uxC5JFEhIBJbsIJd+UHBlwBLX1hukC0l9ISq4lpFnsRqRin4hEjAbUnhS7aJNtMa0oi/n7x89pBxhrQTPlp6gftjy7CLGgFbY/xW1iDSD04mZL/fkqbjMnhS5NA4Xgn1O0elYGSc8feheUxWBaeMvt1CEztBbEuib9ENemNgRWEYl66lFBpekko2fAxLFKwMC0asYr/486r8voMA/N33hOefX0sEVhc/NCk8+iUYAYuKCWDE44NCK6guJzCRIxYuMuLWRfYvO+3VMovheEWsVfQcSac/XWEdJ/e54aewdMKaSyF3SDzr6sWSWmDHm0ghIZQn55+es6czdh5xyLclRTK86NsGsXNkuxwROoDbbWbxnpUYHjFm6JxBiqFGgLw="
    }
  }
}
