{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-discord-config",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-discord-config",
        "namespace": "monitoring"
      }
    },
    "encryptedData": {
      "discord.yaml": "AgCtMx0NOySoupS687xjxy1rWO6D7/IPUQVV9yFWL+4JO9ZTZM2lNmIfy4iPk8cOjeHbpLGRn9rtJHal/rAb0joet5DboPsfDH3UP0W7yhZHGxirmPUjnBrzAn6bLjOqGluLmGHMVJZRiUhrSjwpO59MdmYJF+s4zjlOjfLzKClfdwsa9mazC37cVMjL3lPogqUNxJEbsSwpSJ4lDjDBNfJPPLRlOBlTZr4hiPztED0thtftQjl3w9CgBHUn4PLrn58q6wa86G62Ylx7D2ihC2S827fBvh7ZiBLIdvGlNDVNGrGntpdiY3LdGiuBvyckB2mdN5yb4HZPYAqG9qiY7rCzJciqCmLWTBdnJoXKSi/suRw9fpQBiw052rBq6vBbGxbUpE4Ic5qmwm0EzXGELvDf+VBSvv1zwSLzP16NqeQze6VOWYvYSOHfJ3nFtdz5b7PJoZNrUC3EoyhsWwTrujPhv5Qu3SuNX6amIssMabLUMVms5XMmlnP76A8zDVO/gZtKnz0kPNVXVBLBm4xT21CRgkS0n6t8+8ndZgdAgyi098ZIySrc2NHAR/lvnh1JT/BecMCl0Lzk3xdt4W7ulAOa/DMyStJWIuJ+3SjcW2s6WwFP4jdp1ncBkAmP4WI97fHcruEXMsO4wrZLwJzWjsf4Eb2UvoFEo8+B+X2IwlOa06s1zZggCIGE61NzuUk636aPPEZhAnGCoy8lNcpNsC2rvwq+LD/EIftPMgrdlU/GX1yDcRZGLjBdkMXUE84r5KUl944IR/rN3DVJAFhyJT5bZC+ygQM/00z6xfXWNdcaRgQU7DJd9DxjZeANU0k9wXC5TNsnco13mV5fNR48V7ecU3E7f9A0wIcppeuD3jdCobJzKZ5QoN1hEitbuuQZVqu6GCJBZY7o5IcKZXgoLZKfwxpu5fclf0Ki2luOXdEqNz4XZhACSSTHQBjuG/1NU7ZU9lI7n4c2ZSie1rjaNP8TZK5b7FRBkJsjpXA2N4xBLn50g67glvnGKJOQzZ4+cWzq+d1zWfDbJ0o5D1siU1WZZD0yLhIYokWL+CPPe40wZYuqPo5TWKY="
    }
  }
}
