{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-discord-config",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-discord-config",
        "namespace": "monitoring"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "alertmanager.yaml": "AgAwYZRJtqaxWcFl0l8iEd575gu7LQuEoQUiTIMCyqM3BMW//4w+CvDyGhEf75SIOUTb6aksUlGEKYwJAC6J/O2mxCZbI/44RQHtvs4+e9hwlF6HkUTdfDP/TsFqDiA6IPemCp3erR/TpUdhoy9GRvoU9ZCKztAHof0f0yrqzHcZt/HfNri2r/2sEI9TFdlOnc8tVLV4nqg6a1tU73epFYVeERALb9xv32QeKJq3d0ywR3OkibcF4Sw44Frbnbcs9baMk6HgB3+CUHLJJyLp+e7Vd3zos8UP6dBMiGI3oBYs7t3dU8Bwa7kXqJoxEauvqmuYtOHmrG7h2/iKPMZLiPbyFheUXgBjjT2nd6MUt6uKGbQOyb6sGEH+E5AO0t0MQaCiu1iYAsUBkHsGTDCa1Yg8Ts3tBB49WeUB2L5IDC8QqBiE1EVkqjarckW92zS4FuWZGtTLwnNPmMlScPdLnEYoZeFjtlRPEdQq46J1XaHWIygyWku7aZAGoqkSg5Krv79ZRgISSqCWDsN3KSL7kztjpxuwcj5kvMmrVcoa3mnDgqaR+2drlBXDi9irOapmVB9/4azw6/Oug1aNknarjvT0SXiOtdDcswATgBTLbc9hs/Wf2FixoJKGjFpllQ/GkQOvRaGhW2oLV95pIUvtx3aeyhcoMD79oHEEHrPWQ4PhGU8KhGAePiOyy/4kF3J4nRehSD2u2hiUFuce0gvdnK8lH/57sf/blY/nDc0P+B4bMFv2mGxyzD0LJMLVlnbTyPGafwsok5adrZddqmA4jj9gmqexJ9yAlUAyz6RTLuqRCYUOZ4N4+5qDSh5CW5REnqgQy+jrq9+0UX3bR0435XA/tkbIM2P849p0oMPt8kz82Zjm7TODK5n4OOaXQQl0KONxd/AbgxK7WvIbyHGEs4+QpzmBdB77EaaLk66ElqB+D6JvvfcCK8terLfceAT2POHxzYDtE3MuuKT940JxKaEtg0Wh15nGcFkIgY711hnYT8MAuWVeWh+Yf6dZfrvwvJq2LfubIuZQ5Q1H7reCIt33za41ZLfVrfY7Ln0cC04zwA3f2MK8aYh3xZo+Ht6rjDe28srV2VPCzzx09LiEaONUyoWYB4Sj+KCtDPC80AmAKmaUdv7P+KAg57abMsfhs02p3ulwMNGsFrIkb70lJpLV5iWmVlbFCqvsTP/Br7mIl80C14ky9IXEp54FZJG5xqNz39YyVODFC0FydO4C2eIK12/06nN09woj1QlKzSmkof7Mml8WMwoMAQ83sw0HaC3wmlNGuNS0xkQJpa4PP9ZYfaXHzA7+c0LAoEecDRDgXuzj/QqaQrbJAmJ5YpBkb56+c0hW6sAgAKEjxgKI6lcPPDxxRPdynYqbgQZE9GKiw3Sh0EVfrbBRdrpuQZ8ITkJb7JOTGozpZ5kXn+1LHFbd5uuOtGEaVjZnDY8kDz1jCqWtPcKUvbJZyzR12v39fuqgtXrvO0mwr4thBE+aiComV8jNqTFHa9OoiHMXQ43FCf5dKKNR5fIVF07gL2yeG2st344MM8zUPMivuPt3xM/l2UuLAxjVr/wFdGjWSeW/5YkNwxL5/M1fRNYNmdteF7tl3jnL8uOTp4obv6g5plrPjNAZwSWbw7WNwYY21+uYqUHlv9tL7wNjRSRSVS4VxaFAaZYV08wuC9SFnAGtOXjx6fwxoJGJr2Fk+htnLQsb+mois20fl8x0yanRotjoyAiB0MNCBV39zGveOAOWjHwukUjeTY4NOZe7v3jsXk9DKfZXpehwMqxHu2XQNs6M3dvir1U1nDoci2zNISYtA+p8vmjyVUjTHnSabaiWlLK1P2+kNsD62vlK9ED8ErdWtpwsZ+O45Sv3U7l2hkDvhdPOJJg7sdBdOTKE+/NAoVTgiB6rCinsa+V46KvHLDZX975PqM9leyLsfpQ/zyOZX5pE8G9yEhmIJUKop3Qgik7UybuFQ0SjICarPd7lPEjL1gUNuWcxVp5xAt1qWCuQUPZnqdAIqp0hOxdzK+U6FmNF51LEJTw8SZiR0/XLeT+N6cfglLm0"
    }
  }
}
