{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alertmanager-discord-config",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alertmanager-discord-config",
        "namespace": "monitoring"
      }
    },
    "encryptedData": {
      "discord.yaml": "AgAWIigmudf6yCbe+T0s0PpxUunl9WqwA2OxuhG1ThU53LPlHvIt+ugZDeeOJLfGJrO5opM4HUY8b5ib5+fgpF3KJPau/PyH8Ngsw54ZbLUwGbYXp/Ph+GkDVqED43f+KA7faN4EpNedodGkgMjTVnwfOABtqyhmIohZ9SqHVROXN98zco6XeD74LZlQ9MSD3/3x99M/zF6IVxo4pDqHewaOYnI1XiZkXA3DFTbfjfgD5gsDm/MhMbP/hwtHbMEcwLa9RLlUjBTzf6bag3GQlK0IuzjGzki7iEYPlxRjarM007C6sV1Hlq4Z8VhrWtLh41bVkcaE/KgjzcEWnrxDo3JJMrtczxIFM/O6pf4us6KFQnbupopmVrvGY5UIOubHbxaKh2z/JkDRrBsYdD1An4d6cS5w1qgyLGNB6x7H6Yp47tizet1SeNwduJRc8JVt8KaQyt2X1HaLNy9ljTe2LDpE++/WT62+rrUKyUFYPZU6/ll5sKcTJuEKdbMdN8FKDgSlz4gyC+WkbsLDKB2daVnLRCvSO1ScjnIcKqYMxlF7Ljh/Kl41BhuKO2jSu2ykwQ6r8SkI62Iw16b7xJJtAN1Bf2JZEJxw+FEj6oEIswH0GSezPdBWk/Y+xqX1wXslOod9BxT2w1Mxpc75sSQufQ9Bdv4Bh95ezrrRy9bZ1D8s/BhstLzvvRdRl/KZB5Vv/PioxHi6tk5mkjHQdmnfkQqYs5VTIcaEA182VKgQo0wLH9ehexFwcx/77zTzpTlIdxmp+0sgpJ3gbesHk5+gKyKCCwmmQBGhhhy3GwHPQD9Zt3GWZhGYhUAYj/rTksFhx2zH6z9nZV4w2JVQV+GsKIgLPsNQ/rXb9NnAt+wzjcPYYAw0KqTPnLu8oYQnGivMB1NgswOBlGsxlwI4eaB+CMHMJlpcVVmcmd86b87CLYJsPARxyM4ZA6FyR4Wbq/+EZP/HgbZd75skGtLTSWYv4LgEtrDJ/CnGnayQPm9B/tJ9k3vk6S74P2YIKNyf+9Lpic+Ycjm5+ONDGBPcG9vwpnzhyEMEs3CW9Av26kfXD59bRoR+/GY0NUPwWGmhULsNA+gOW8LlMERnXr3ujdkQtBUFW1ZIAoskZwGIrLpDaa4PeaYbSBsVo9yhmphL6CYd12N5zfrS6xSHF2taeLUG2ctivUxvPW6twUDrkBGf6YpExUBM+zD8lJJbAuNLb0vq6jS3FokeyCPFy2JdmQ4n2PalI3BOmZ54sgatKFtRE13sGPCU0tjl/WjAY3f1Cn0y5ZvePw1IkPYD5NzeBmr6CTMubWPmq80="
    }
  }
}
