apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: etcd-scrape-config
  namespace: monitoring
spec:
  jobName: etcd
  targetEndpoints:
    - targets: ["192.168.10.50:2381", "192.168.10.51:2381", "192.168.10.512:2381"]