apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-plugins-pvc
  namespace: monitoring
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi