apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: oci://quay.io/jetstack/charts
    targetRevision: v1.21.0
    chart: cert-manager
    helm:
      releaseName: cert-manager
  - repoURL: https://github.com/metalnet/infra
    targetRevision: HEAD
    path: kube/certmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      enabled: true
    syncOptions:
      - CreateNamespace=true

