apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minecraft
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: minecraft
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: minecraft
  source:
    repoURL: https://github.com/metalnet/infra.git
    path: kube/minecraft
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
