---
- name: mount storage
  mount:
    path: /export
    src: /dev/vdb
    fstype: auto
    state: mounted
- name: install nfs
  package:
    name: nfs-kernel-server
    state: present
- name: configure nfs exports
  lineinfile:
    path: /etc/exports
    regexp: '^/export\s'
    line: /export       192.168.1.0/24(rw,sync,fsid=0,no_subtree_check,no_root_squash)
    state: present
  notify: restart nfs service
