enableRbac: true
serviceAccount:
  create: true

config:
  bookmarks: {}
  widgets: {}
  services:
    - Infrastructure:                                                                     
        - OPNSense:                 
            href: https://opnsense.metalnet.org

  kubernetes:
    mode: cluster
    ingress: false
    traefik: true
    gateway: true

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "www.metalnet.org,metalnet.org,homepage.kube.metalnet.org,homepage"
