image:
  repository: ghcr.io/gethomepage/homepage
  tag: v2.2.0@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd

enableRbac: true
serviceAccount:
  create: true

config:
  bookmarks: {}
  widgets: {}
  services:
    - Infrastructure:                                                                     
        - OPNSense:                 
            href: https://opnsense.metalnet.org

  kubernetes:
    mode: cluster
    ingress: false
    traefik: true
    gateway: true

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: "www.metalnet.org,metalnet.org,homepage.kube.metalnet.org,homepage"
