#cloud-config
hostname: ${hostname}
manage_etc_hosts: true
ssh_authorized_keys:
  - ${pubkey}
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
packages:
  - qemu-guest-agent
runcmd:
  - /usr/sbin/invoke-rc.d qemu-guest-agent start
  - /usr/sbin/invoke-rc.d networking force-reload
