ingressClass:
  enabled: false
experimental:
  kubernetesGateway:
    enabled: true
api:
  insecure: true
providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  enabled: false
ports:
  metrics:
    expose:
      default: true
