ingressClass:
  enabled: false
experimental:
  kubernetesGateway:
    enabled: true
api:
  insecure: true
providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  enabled: false
metrics:
  influxDB2:
    address: "http://vmsingle-vmks:8428"
    token: "dummy_token"
    org: "dummy_org"
    bucket: "dummy_bucket"
    pushInterval: 10s
    addEntryPointsLabels: true
    addServicesLabels: true

