ingressClass:
  enabled: false
experimental:
  kubernetesGateway:
    enabled: true
api:
  insecure: true
providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  enabled: false
ports:
  metrics:
    expose:
      metrics: true
service:
  additionalServices:
    metrics:
      type: ClusterIP
      ports:
        - name: metrics
          port: 9100
          targetPort: metrics
          protocol: TCP