apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: minecraft-gateway
  namespace: minecraft
spec:
  gatewayClassName: traefik
  listeners:
    - name: minecraft-tcp
      protocol: TCP
      port: 25565
      allowedRoutes:
        namespaces:
          from: Same
    - name: minecraft-udp
      protocol: UDP
      port: 25565
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: minecraft-tcp-route
  namespace: minecraft
spec:
  parentRefs:
    - name: minecraft-gateway
      namespace: minecraft
      sectionName: minecraft-tcp
  rules:
    - backendRefs:
        - name: mc-router
          port: 25565
          protocol: TCP
          kind: Service
          group: ""
      matches:
        - rules:
            type: HostSNI
            value: "*"
---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: minecraft-udp-route
  namespace: minecraft
spec:
  parentRefs:
    - name: minecraft-gateway
      namespace: minecraft
      sectionName: minecraft-udp
  rules:
    - backendRefs:
        - name: mc-router
          port: 25565
          protocol: UDP
          kind: Service
          group: ""
