systemIp: unifi.metalnet.org

service:
  type: LoadBalancer
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.71
    metallb.io/allow-shared-ip: unifi 

persistence:
  data:
    size: 10Gi
  mongo:
    size: 10Gi
  backups:
    enabled: true
    size: 20Gi