---
- name: mount nfs share
  mount:
    fstype: nfs
    src: mnshare:/
    path: /mnt
    opts: 
    state: mounted
  changed_when: false
- name: setup data directory
  file:
    path: "/mnt/{{ volume_path }}"
    mode: '0777'
    state: directory
- name: unmount nfs share
  mount:
    path: /mnt
    state: unmounted
  changed_when: false
- name: copy stack configuration
  copy:
    src: "../stacks/{{ stack_file_name }}"
    dest: "~/{{ stack_file_name }}"
- name: deploy stack
  docker_stack:
    name: "{{ name }}"
    compose:
      - "~/{{ stack_file_name }}"
