apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-my-pvc
  namespace: velero
spec:
  includedNamespaces:
  - monitoring
  includedResources:
  - persistentvolumeclaims
  - persistentvolumes