apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: monitoring-backup
  namespace: velero
spec:
  schedule: "0 2 * * *" 
  template:
    includedNamespaces:
      - monitoring
    snapshotVolumes: true
    snapshotMoveData: true
