configuration:
  features: EnableCSI
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: metalnet-kube
      config:
        s3Url: https://s3.ca-east-006.backblazeb2.com
        region: ca-east-006
        s3ForcePathStyle: true
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: ca-east-006
credentials:
  useSecret: true
  existingSecret: velero-cloud-credentials
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.14.2@sha256:0751144c1c8e52d52c48717fbd13ad5a3061e612ae4d7ad744a946cd5b139d1a
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
#defaultVolumesToFsBackup: true
snapshotsEnabled: true
deployNodeAgent: true