---
version: "3.3"

services:
  syncthing:
    image: syncthing/syncthing
    volumes:
      - data:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.syncthing.entrypoints=web
        - traefik.http.routers.syncthing.rule=Host(`syncthing`)
        - traefik.http.services.syncthing.loadbalancer.server.port=8384
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  data:
    driver_opts:
      type: "nfs"
      device: ":/syncthing"
      o: "addr=mnshare,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
