apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: traefik-scrape-config
  namespace: monitoring
spec:
  jobName: traefik
  targetEndpoints:
    - targets: ["192.168.10.70:9100"]