apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma-reconciler
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/mshogren/uptime-kuma-reconciler
    targetRevision: HEAD
    path: charts/uptime-kuma-reconciler
    helm:
      releaseName: uptime-kuma-reconciler
      valueFiles:
      - $values/kube/monitoring/uk-reconciler/values.yaml
  - repoURL: https://github.com/metalnet/infra.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/metalnet/infra
    targetRevision: HEAD
    path: kube/monitoring/uk-reconciler
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      enabled: true

