nameOverride: vmks
defaultDashboards:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    
vlsingle:
  enabled: true
  spec:
    retentionPeriod: 30d
    storage:
      resources:
        requests:
          storage: 30Gi
          
vlagent:
  enabled: true
  spec:
    k8sCollector:
      enabled: true
      
grafana:
  plugins:
    - victoriametrics-logs-datasource
