---
- name: install required package for signing package repositories  
  package:
    name: gnupg-agent
    state: present
- name: add docker signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    filename: docker
    state: present 
- name: install packages
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - nfs-common
    - cifs-utils
    - python3-pip
- name: install pip packages for ansible to use
  pip:
    name: [docker, jsondiff, pyyaml]
    state: present
- name: initialize swarm
  docker_swarm:
    state: present
