---
- name: vyos
  hosts:
    - vyos
  remote_user: vyos
  roles:
    - vyos
- name: mnjump
  hosts:
    - mnjump
  roles:
    - common
    - jumphost
- name: mnshare
  hosts:
    - mnshare
  remote_user: debian
  become: true
  roles:
    - common
    - nfs
    - samba
- name: mnapps
  hosts:
    - mnapps
  become: true
  remote_user: debian
  roles:
    - role: common
    - role: traefik
    - role: rancher
    - role: docker-stack
      vars:
        name: portainer
        volume_path: portainer
        stack_file_name: portainer.yml
    - role: docker-stack
      vars:
        name: nginx
        volume_path: nginx
        stack_file_name: nginx.yml
