deployment:
  kind: DaemonSet
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: ""
ingressClass:
  enabled: false
experimental:
  kubernetesGateway:
    enabled: true
api:
  insecure: true
providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  enabled: false
ports:
  metrics:
    expose:
      default: true
  kms:
    port: 1688
    exposedPort: 1688
    protocol: TCP
    expose:
      default: true
  minecraft-tcp:
    port: 25565
    exposedPort: 25565
    protocol: TCP
    expose:
      default: true
  minecraft-udp:
    port: 25565
    exposedPort: 25565
    protocol: UDP
    expose:
      default: true
service:
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.70