deployment:
  kind: DaemonSet
updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: ""
ingressClass:
  enabled: false
experimental:
  kubernetesGateway:
    enabled: true
api:
  insecure: true
providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  enabled: false
ports:
  metrics:
    expose:
      metrics: true
  kms:
    port: 1688
    exposedPort: 1688
    protocol: TCP
    expose:
      kms: true
  minecraft-tcp:
    port: 25565
    exposedPort: 25565
    protocol: TCP
    expose:
      minecraft-tcp: true
  minecraft-udp:
    port: 25565
    exposedPort: 25565
    protocol: UDP
    expose:
      minecraft-udp: true
  mqtt:
    port: 1883
    exposedPort: 1883
    protocol: TCP
    expose:
      mqtt: true
  mqtts:
    port: 8883
    exposedPort: 8883
    protocol: TCP
    expose:
      mqtts: true
  syslog-tcp:
    port: 514
    exposedPort: 514
    protocol: TCP
    expose:
      syslog-tcp: true
  syslog-udp:
    port: 514
    exposedPort: 514
    protocol: UDP
    expose:
      syslog-udp: true
service:
  annotations:
    metallb.io/loadBalancerIPs: 192.168.10.70
  additionalServices:
    metrics:
      labels:
        app.kubernetes.io/instance: traefik-metrics
      type: ClusterIP
      ports:
        - name: metrics
          port: 9100
          targetPort: metrics
          protocol: TCP