ingressClass:
  enabled: false
experimental:
  kubernetesGateway:
    enabled: true
api:
  insecure: true
providers:
  kubernetesIngress:
    enabled: false
  kubernetesCRD:
    allowExternalNameServices: true
  kubernetesGateway:
    enabled: true
    experimentalChannel: true
gateway:
  enabled: false
ports:
  metrics:
    expose:
      metrics: true
  kms:
    port: 1688
    exposedPort: 1688
    protocol: TCP
    expose:
      kms: true
  minecraft-tcp:
    port: 25565
    exposedPort: 25565
    protocol: TCP
    expose:
      minecraft-tcp: true
  minecraft-udp:
    port: 25565
    exposedPort: 25565
    protocol: UDP
    expose:
      minecraft-udp: true
service:
  additionalServices:
    metrics:
      labels:
        app.kubernetes.io/instance: traefik-metrics
      type: ClusterIP
      ports:
        - name: metrics
          port: 9100
          targetPort: metrics
          protocol: TCP