apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: ipmi-tls-transport
  namespace: traefik
spec:
  serverName: ipmi.metalnet.org
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: ipmi-service
  namespace: traefik
spec:
  type: ExternalName
  externalName: ipmi.metalnet.org
  ports:
    - name: https
      port: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ipmi-tls-cert
  namespace: traefik
spec:
  secretName: ipmi-kube-metalnet-org-tls
  issuerRef:
    name: cloudflare-acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - ipmi.kube.metalnet.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ipmi-route
  namespace: traefik
  annotations:
    gethomepage.dev/href: "https://ipmi.kube.metalnet.org"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/name: Intelligent Platform Management Interface
    gethomepage.dev/app: ipmi-service
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ipmi.kube.metalnet.org`)
      kind: Rule
      services:
        - name: ipmi-service
          port: 443
          serversTransport: ipmi-tls-transport
  tls:
    secretName: ipmi-kube-metalnet-org-tls

