---
- name: install samba
  package:
    name: samba
    state: present
- name: configure samba
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [media]
          path = /smb
          read only = no
          browsable = yes
  notify: restart smbd service
- name: add samba user
  shell:
    cmd: echo 'samba' > smbpasswd -s -a debian
  notify: restart smbd service
